name: Test
on: [push]
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install helm
      run: |
          wget -nv https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.0.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/bin
          helm version
          rm -rf helm-*

    - name: Package chart
      run: |
          mkdir -p /tmp/out
          helm package -d /tmp/out ./cert-manager-rds
          helm repo index /tmp/out
          ls -alh /tmp/out

    - name: Publish
      run: |
          git checkout gh-pages
