name: Publish
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install helm + package chart
      run: |
          mkdir -p /tmp/out
          helm package -d /tmp/out ./cert-manager-crds
          helm repo index /tmp/out
          ls -alh /tmp/out

    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git checkout gh-pages
          cp /tmp/out/* .
          git config user.name "Robot"
          git config user.email "robot@rocketeer.be"
          git add .
          git commit -a -m "Update chart repository"
          git push
