name: Publish
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install helm + package chart
      run: |
          wget -nv https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.0.0-linux-amd64.tar.gz
          echo $PATH
          mv linux-amd64/helm /tmp
          helm version
          rm -rf helm-*

          mkdir -p /tmp/out
          /tmp/helm package -d /tmp/out ./cert-manager-rds
          /tmp/helm repo index /tmp/out
          ls -alh /tmp/out

    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git checkout gh-pages
          cp /tmp/out/* .
          git config user.name "Robot"
          git config user.email "robot@rocketeer.be"
          git add .
          git commit -a -m "Update chart repository"
          git push
